name: Nightly Documents Update

on:
  push: 
  schedule:
    # schedule on nighly run at 00:00 local Swedish time (23:00 UTC)
    - cron: '02 23 * * *'

jobs:

  make_html:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository Content
        uses: actions/checkout@v2
      - name: Set Up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '2.x' 
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Installl Dependencies
        run: pip install sphinx sphinx_rtd_theme m2r mistune==0.8.4
      - name: Build Files
        run: make html
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: folder_html
          path: html
          retention-days: 1

  publish_html:
      needs: make_html
      runs-on: ubuntu-latest
      steps:
      - name: Get Access Permit
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Download Artifacts from Job "make_html"
        uses: actions/download-artifact@v2
        with:
          name: folder_html
          path: ./
      - name: Init Git & Set User
        run: |
          git init
          git config user.email "jenkinzhang@outlook.com"
          git config user.name "halajun"
      - name: Git Add & Commit
        run: |
          git add .
          git commit -m "nightly or push update on `date +'%Y-%m-%d'`"
      - name: Add Remote & Force Push
        run: |
          git remote add origin git@github.com:smarc-project/smarc-project.github.io.git
          git push -f origin master

  

